
spring:
  datasource:
    name: test  #���ݿ���
    url: jdbc:mysql://192.168.21.128:3306/User #url
    username: root  #�û���
    password: ''  #����
    driver-class-name: com.mysql.cj.jdbc.Driver  #���ݿ���������
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml  #����ӳ���ļ�
  type-aliases-package: com.example.test.bean #����ʵ����
